"""initital

Revision ID: aec4f42b746d
Revises: 
Create Date: 2025-09-12 23:39:03.986232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec4f42b746d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('cod_projeto', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_encerramento', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('situacao', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('cod_projeto')
    )
    op.create_table('requisitions',
    sa.Column('cod_requisicao', sa.Integer(), nullable=False),
    sa.Column('cod_projeto', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('data_solicitacao', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['cod_projeto'], ['projects.cod_projeto'], ),
    sa.PrimaryKeyConstraint('cod_requisicao')
    )
    op.create_table('orders',
    sa.Column('cod_ordem', sa.Integer(), nullable=False),
    sa.Column('cod_requisicao', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('situacao', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['cod_requisicao'], ['requisitions.cod_requisicao'], ),
    sa.PrimaryKeyConstraint('cod_ordem')
    )
    op.create_table('contracts',
    sa.Column('num_contrato', sa.String(length=20), nullable=False),
    sa.Column('cod_ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=400), nullable=True),
    sa.Column('cpfcnpj', sa.String(length=20), nullable=True),
    sa.Column('contratado', sa.String(length=200), nullable=True),
    sa.Column('tipo_pessoa', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('parcelas', sa.Integer(), nullable=True),
    sa.Column('situacao', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['cod_ordem'], ['orders.cod_ordem'], ),
    sa.PrimaryKeyConstraint('num_contrato'),
    sa.UniqueConstraint('cod_ordem')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cod_ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['cod_ordem'], ['orders.cod_ordem'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_contrato', sa.String(length=20), nullable=False),
    sa.Column('num_parcela', sa.Integer(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('valor_parcela', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['num_contrato'], ['contracts.num_contrato'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installments')
    op.drop_table('order_items')
    op.drop_table('contracts')
    op.drop_table('orders')
    op.drop_table('requisitions')
    op.drop_table('projects')
    # ### end Alembic commands ###
